// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDfDKHI4ahmlTUb-wD_wDylpB5yP1II14',
    appId: '1:663489939418:web:150bff9f2529b53a5262e3',
    messagingSenderId: '663489939418',
    projectId: 'avaliafisiotcc',
    authDomain: 'avaliafisiotcc.firebaseapp.com',
    storageBucket: 'avaliafisiotcc.appspot.com',
    measurementId: 'G-68C6TLG72D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqi8zaJ8z0JHpoSnLoya42O8Hu4uXgV2s',
    appId: '1:663489939418:android:63b41fc131cc64805262e3',
    messagingSenderId: '663489939418',
    projectId: 'avaliafisiotcc',
    storageBucket: 'avaliafisiotcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2JW4HhLankGju2t29khk6cQUt2_m9HaI',
    appId: '1:663489939418:ios:010f65bf37d3c44f5262e3',
    messagingSenderId: '663489939418',
    projectId: 'avaliafisiotcc',
    storageBucket: 'avaliafisiotcc.appspot.com',
    iosClientId: '663489939418-ptve4cpnmdnpe5694kncgtg8jua5tek0.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoTcc2',
  );
}
